import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import NXProvider from "./nextui_provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NXProvider>
        <body className="">
          <NavBar />
          {children}
        </body>
      </NXProvider>
    </html>
  );
}
